title: フランスPhDメモ
description: Inria（フランス国立情報学自動制御研究所）での博士生活を残すためのブログ。

markdown: kramdown
url: "https://juri-ynym.github.io"
baseurl: "/blog"

# for atom feed
author:
  name: Juri Yoneyama
  email: 

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md","/templates"]

permalink: /:category/:title/

